# Generated by Django 4.1 on 2022-08-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiar3',
            new_name='Familiar',
        ),
    ]
